"use client";

import { getToken } from "@/lib/api/credentials";
import { ProjectActivityTypes } from "@/types/project-management-types";
import CardComponent from "@/ui/card-wrapper";
import Button from "@/ui/form/button";
import DateInput from "@/ui/form/date-input";
import TagInput from "@/ui/form/tag-input";
import TextInput from "@/ui/form/text-input";
import TextareaInput from "@/ui/form/textarea";
import Heading from "@/ui/text-heading";
import { formatDate } from "@/utils/dates-format-utility";
import axios from "axios";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";

// for prefill sections
function PrefilledInput ({ text, label } : { text: string | number; label?: string }) {
  return (
    <div className="space-y-2">
      <label className="text-[#101928] text-sm font-medium mb-2">{ label }</label>
      <div className="w-full border border-gray-300 rounded-md p-3 text-sm cursor-not-allowed text-gray-400">
        <div className="bg-[#EFEFEF] p-2 rounded w-fit">
          { text }
        </div>
      </div>
    </div>
  )
}

interface ActivityReportPayload {
  activityReportId: string;
  activityId: string;
  percentageCompletion: number;
  actualStartDate: string;
  actualEndDate: string;
  actualCost: number;
  actualNarrative: string;
}

interface PercentageOption {
  id: string;
  label: string;
  minValue: number;
  maxValue?: number;
  isRange?: boolean;
}

export default function AddActivityReport() {
  const params = useParams();
  const activityId = params.activityId as string;
  const [activity, setActivity] = useState<ProjectActivityTypes[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const token = getToken();

  // Form state
  const [formData, setFormData] = useState<Omit<ActivityReportPayload, 'activityReportId' | 'activityId'>>({
    percentageCompletion: 0,
    actualStartDate: "",
    actualEndDate: "",
    actualCost: 0,
    actualNarrative: ""
  });

  // Percentage completion options
  const percentageOptions: PercentageOption[] = [
    { id: "0", label: "Not Started (0%)", minValue: 0 },
    { id: "1", label: "Preliminary progress (1% - 29%)", minValue: 1, maxValue: 29, isRange: true },
    { id: "30", label: "Mid Progress (30% - 50%)", minValue: 30, maxValue: 50, isRange: true },
    { id: "51", label: "Advanced Progress (51% - 69%)", minValue: 51, maxValue: 69, isRange: true },
    { id: "70", label: "Near Completion (70% - 99%)", minValue: 70, maxValue: 99, isRange: true },
    { id: "100", label: "Fully Completed (100%)", minValue: 100 }
  ];

  // automatically fetch activities for prefilling
  useEffect(() => {
    const fetchActivities = async () => {
      try {
        const response = await axios.get(
          `${process.env.NEXT_PUBLIC_BASE_URL}/api/projectManagement/activities`,
        );
        setActivity(response.data.data);
      } catch (error) {
        toast.error("An error occured. Please try again.");
        console.log(error);
      }
    };
    fetchActivities();
  }, []);

  // Handle form input changes
  const handleInputChange = (field: keyof typeof formData, value: string | number) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // Handle percentage completion change
  const handlePercentageChange = (option: PercentageOption) => {
    // Store the minimum value as requested
    setFormData(prev => ({
      ...prev,
      percentageCompletion: option.minValue
    }));
  };

  // Handle date changes
  const handleDateChange = (field: 'actualStartDate' | 'actualEndDate', date: string) => {
    // Convert to ISO string with time
    const isoDate = date ? new Date(date).toISOString() : "";
    handleInputChange(field, isoDate);
  };

  // Handle submit
  const handleSubmit = async () => {
    // Validate required fields
    if (!formData.percentageCompletion) {
      toast.error("Please select a percentage completion");
      return;
    }

    if (!formData.actualStartDate) {
      toast.error("Please select an actual start date");
      return;
    }

    if (!formData.actualEndDate) {
      toast.error("Please select an actual end date");
      return;
    }

    if (!formData.actualCost || formData.actualCost <= 0) {
      toast.error("Please enter a valid actual cost");
      return;
    }

    if (!formData.actualNarrative.trim()) {
      toast.error("Please enter an activity narrative");
      return;
    }

    try {
      setIsSubmitting(true);
      
      const payload = {
        isCreate: true,
        payload: {
          activityReportId: "", // Will be generated by the backend
          activityId,
          ...formData,
          actualCost: Number(formData.actualCost) // Ensure it's a number
        }
      };

      const response = await axios.post(
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/projectManagement/activity-report`,
        payload,
         {
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${token}`,
            },
          }
      );

      if (response.data.success) {
        toast.success("Activity report added successfully!");
        // Reset form or redirect
        setFormData({
          percentageCompletion: 0,
          actualStartDate: "",
          actualEndDate: "",
          actualCost: 0,
          actualNarrative: ""
        });
        window.history.back();
      } else {
        toast.error(response.data.message || "Failed to add activity report");
      }
    } catch (error: any) {
      console.error("Error submitting form:", error);
      toast.error(error.response?.data?.message || "An error occurred. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  // get activity to prefill form
  const selectedActivityToPrefillForm = activity.find((act) => act.activityId === activityId);
  if (!selectedActivityToPrefillForm) return null;

  return (
    <div className="w-156">
      <CardComponent>
        <Heading
          heading="Activity Reporting Format and Attributes"
          className="text-center"
        />
        <div className="space-y-6 my-6">
          <PrefilledInput text={selectedActivityToPrefillForm.activityStatement} label="Activity Statement" />
          <PrefilledInput text={selectedActivityToPrefillForm.outputStatement} label="Linked to Output" />
          <PrefilledInput text={`₦ ${selectedActivityToPrefillForm.activityTotalBudget}`} label="Activity Total Budget" />
          <PrefilledInput text={selectedActivityToPrefillForm.responsiblePerson} label="Responsible Person(s)" />
          <p className="text-gray-900 font-bold text-base">Activity Frequency</p>
          <PrefilledInput text={selectedActivityToPrefillForm.subActivity} label="Type" />
          <PrefilledInput text={formatDate(selectedActivityToPrefillForm.deliveryDate, "date-only")} label="Delivery Date" />
          <PrefilledInput text={selectedActivityToPrefillForm.descriptionAction} label="Description" />
          <p className="text-gray-900 font-bold text-base">Action 1: Percent completion (%)</p>

          {/* percentage boxes */}
          <div className="grid grid-cols-2 gap-5 text-sm">
            {percentageOptions.map((option) => (
              <div key={option.id} className="flex items-center gap-2">
                <input 
                  type="radio" 
                  name="percentageCompletion" 
                  id={option.id} 
                  className="size-4 accent-(--primary)"
                  checked={formData.percentageCompletion === option.minValue}
                  onChange={() => handlePercentageChange(option)}
                />
                <label htmlFor={option.id}>{option.label}</label>
              </div>
            ))}
          </div>
          
          <div className="flex items-center gap-2">
            <DateInput 
              label="Activity Actual Start Date" 
              value={formData.actualStartDate ? new Date(formData.actualStartDate).toISOString().split('T')[0] : ""}
              onChange={(value) => handleDateChange('actualStartDate', value)}
            />
            <DateInput 
              label="Activity Actual End Date" 
              value={formData.actualEndDate ? new Date(formData.actualEndDate).toISOString().split('T')[0] : ""}
              onChange={(value) => handleDateChange('actualEndDate', value)}
            />
          </div>
          <TextInput
            name="actualCost"
            label="Activity Actual Cost (N)"
            value={formData.actualCost.toString()}
            onChange={(e) => handleInputChange('actualCost', e.target.value)}
          />
          <TextareaInput
            label="Activity Narrative"
            name="actualNarrative"
            value={formData.actualNarrative}
            onChange={(e) => handleInputChange('actualNarrative', e.target.value)}
          />
          <div className="flex items-center gap-8">
            <Button 
              content="Cancel" 
              isSecondary 
              onClick={() => window.history.back()} 
              isDisabled={isSubmitting}
            />
            <Button 
              content={"Add"} 
              onClick={handleSubmit}
              isLoading={isSubmitting}
              isDisabled={isSubmitting}
            />
          </div>
        </div>
      </CardComponent>
    </div>
  );
}