import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/context/SidebarContext";
import { ProjectsProvider } from "@/context/ProjectsContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "NDSICDE M&E Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/images/NDSICDE-logo-small.svg",
    shortcut: "/images/NDSICDE-logo-small.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <ProjectsProvider>
          <SidebarProvider>
            {children}
          </SidebarProvider>
        </ProjectsProvider>
      </body>
    </html>
  );
}
